### ISSUE TITLE
Include Deuterocanon

### ISSUE THREAD

**Issue by Renddslow** [TehShrike/world-english-bible#3]
I was wondering if you’d be open to including a few books from the deuterocanon? The files are in the HTML but not built in the build-html

**Comment by TehShrike** [comment]
I don't want to maintain any data related to the deuterocanon (this came up a while back [in `verse-reference-regex` too](https://github.com/TehShrike/verse-reference-regex/issues/1)), especially since this repo is coupled to the [`books-of-the-bible`](https://github.com/TehShrike/books-of-the-bible) package.

However, if you fork this repo and publish a version that includes the deterocanon, or a version with just the deuterocanon, I'd be happy to link to it.
